(ns com.microsoft.azure.storage.file.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.microsoft.azure.storage.file.CloudFile])
(require '[com.microsoft.azure.storage.file.CloudFileClient])
(require '[com.microsoft.azure.storage.file.CloudFileDirectory])
(require '[com.microsoft.azure.storage.file.CloudFileShare])
(require '[com.microsoft.azure.storage.file.CopyState])
(require '[com.microsoft.azure.storage.file.CopyStatus])
(require '[com.microsoft.azure.storage.file.DeleteShareSnapshotsOption])
(require '[com.microsoft.azure.storage.file.FileDirectoryProperties])
(require '[com.microsoft.azure.storage.file.FileInputStream])
(require '[com.microsoft.azure.storage.file.FileOutputStream])
(require '[com.microsoft.azure.storage.file.FileProperties])
(require '[com.microsoft.azure.storage.file.FileRange])
(require '[com.microsoft.azure.storage.file.FileRequestOptions])
(require '[com.microsoft.azure.storage.file.FileServiceProperties])
(require '[com.microsoft.azure.storage.file.FileSharePermissions])
(require '[com.microsoft.azure.storage.file.FileShareProperties])
(require '[com.microsoft.azure.storage.file.ListFileItem])
(require '[com.microsoft.azure.storage.file.ShareListingDetails])
(require '[com.microsoft.azure.storage.file.ShareStats])
(require '[com.microsoft.azure.storage.file.SharedAccessFileHeaders])
(require '[com.microsoft.azure.storage.file.SharedAccessFilePermissions])
(require '[com.microsoft.azure.storage.file.SharedAccessFilePolicy])
